# 1) deps: ставим зависимости
FROM node:20-alpine AS deps
WORKDIR /app

COPY package.json ./
RUN npm install

# 2) dev: копируем модули + исходники
FROM node:20-alpine AS dev
WORKDIR /app

COPY --from=deps /app/node_modules ./node_modules
COPY . .

EXPOSE 5173
CMD ["npm", "run", "dev"]
