version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: crepeo-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: crepeo-server
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "${PORT}:5000"
    depends_on:
      - mongo
    volumes:
      - ./server:/app
      - /app/node_modules

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: crepeo-client
    restart: unless-stopped
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - ./client:/app
      - /app/node_modules

volumes:
  mongo-data:
